#!/bin/sh
# Draw the Kilobyte logo again in case the graphics driver resized the console.
PREREQ=""
prereqs() { echo "$PREREQ"; }
case $1 in prereqs) prereqs; exit 0 ;; esac
[ -x /usr/lib/kilobyte/bootlogo ] && /usr/lib/kilobyte/bootlogo again > /dev/console 2>&1
exit 0
