# This data file was generated by the Spreadsheet Calculator Improvised (sc-im)
# You almost certainly shouldn't edit it.

format A 16 2 0
format B 10 2 0
leftstring A0 = "Monthly budget"
leftstring A2 = "Rent"
leftstring A3 = "Food"
leftstring A4 = "Internet"
leftstring A5 = "Books"
leftstring A7 = "Total"
leftstring A8 = "Per day"
rightstring B1 = "Amount"
let B2 = 650
let B3 = 280
let B4 = 35
let B5 = 20
let B7 = @sum(B2:B5)
let B8 = B7/30
