#!/usr/bin/env python3
"""Generate Kilobyte's colour themes into rootfs/usr/share/kilobyte/themes.

Each theme is a dialogrc (the colours of every dialog(1) element), an mc skin
name and optionally a 16-colour Linux console palette. Colours are limited to
what a DOS text screen had: 8 background colours, 16 foreground colours (a
"bright" foreground is the ON flag).

Run it after editing this file:  python3 tools/make-themes.py
"""
import os

ROOT = os.path.join(os.path.dirname(__file__), "..", "rootfs", "usr", "share", "kilobyte", "themes")

# ANSI order (as the console uses it): black red green yellow blue magenta cyan white,
# then the bright versions.
CGA = "000000 aa0000 00aa00 aa5500 0000aa aa00aa 00aaaa aaaaaa 555555 ff5555 55ff55 ffff55 5555ff ff55ff 55ffff ffffff"


def mono(dark, mid, bright):
    """A monochrome CRT palette: everything becomes a shade of one phosphor."""
    shades = {"k": "000000", "d": dark, "m": mid, "b": bright}
    #          blk red grn yel blu mag cyn wht | gry red grn yel blu mag cyn wht
    layout = "k   d   m   m   d   d   m   m     d   m   b   b   m   m   b   b".split()
    return " ".join(shades[x] for x in layout)


def rc(t):
    """Expand a compact role table into a full dialogrc."""
    c = dict(t)
    lines = [
        "# Kilobyte theme: generated by tools/make-themes.py, do not edit",
        "aspect = 0",
        "separate_widget = \"\"",
        "tab_len = 0",
        "visit_items = OFF",
        f"use_shadow = {c.get('shadow_on', 'ON')}",
        "use_colors = ON",
    ]
    roles = {
        "screen_color": c["screen"],
        "shadow_color": c.get("shadow", "(BLACK,BLACK,OFF)"),
        "dialog_color": c["dialog"],
        "title_color": c["title"],
        "border_color": c["border"],
        "border2_color": c["border2"],
        "button_active_color": c["btn_on"],
        "button_inactive_color": c["btn_off"],
        "button_key_active_color": c["btn_key_on"],
        "button_key_inactive_color": c["btn_key_off"],
        "button_label_active_color": c["btn_on"],
        "button_label_inactive_color": c["btn_off"],
        "inputbox_color": c["input"],
        "inputbox_border_color": c["border"],
        "inputbox_border2_color": c["border2"],
        "searchbox_color": c["dialog"],
        "searchbox_title_color": c["title"],
        "searchbox_border_color": c["border"],
        "searchbox_border2_color": c["border2"],
        "position_indicator_color": c["title"],
        "menubox_color": c["dialog"],
        "menubox_border_color": c["border2"],
        "menubox_border2_color": c["border"],
        "item_color": c["item"],
        "item_selected_color": c["sel"],
        "tag_color": c["tag"],
        "tag_selected_color": c["sel_tag"],
        "tag_key_color": c["key"],
        "tag_key_selected_color": c["sel_key"],
        "check_color": c["item"],
        "check_selected_color": c["sel"],
        "uarrow_color": c["arrow"],
        "darrow_color": c["arrow"],
        "itemhelp_color": c["status"],
        "form_active_text_color": c["input"],
        "form_text_color": c["dialog"],
        "form_item_readonly_color": c["tag"],
        "gauge_color": c["gauge"],
    }
    lines += [f"{k} = {v}" for k, v in roles.items()]
    return "\n".join(lines) + "\n"


THEMES = {
    # EDIT.COM / QBasic / Turbo Vision: blue desk, gray boxes, cyan status line.
    "classic": dict(
        name="Classic Blue (EDIT.COM)", mc="default", palette=CGA,
        screen="(CYAN,BLUE,ON)", dialog="(BLACK,WHITE,OFF)", title="(BLUE,WHITE,OFF)",
        border="(WHITE,WHITE,ON)", border2="(BLACK,WHITE,OFF)",
        btn_on="(WHITE,BLUE,ON)", btn_off="(BLACK,WHITE,OFF)",
        btn_key_on="(YELLOW,BLUE,ON)", btn_key_off="(RED,WHITE,OFF)",
        input="(WHITE,BLUE,ON)", item="(BLACK,WHITE,OFF)", sel="(WHITE,BLACK,ON)",
        tag="(BLUE,WHITE,OFF)", sel_tag="(YELLOW,BLACK,ON)", key="(RED,WHITE,OFF)",
        sel_key="(RED,BLACK,ON)", arrow="(GREEN,WHITE,ON)", status="(BLACK,CYAN,OFF)",
        gauge="(BLUE,WHITE,ON)",
    ),
    # Norton Commander: black desk, blue panels with cyan text, cyan bar.
    "norton": dict(
        name="Norton Commander", mc="double-lines", palette=CGA,
        screen="(CYAN,BLACK,OFF)", dialog="(CYAN,BLUE,ON)", title="(YELLOW,BLUE,ON)",
        border="(CYAN,BLUE,ON)", border2="(CYAN,BLUE,OFF)",
        btn_on="(BLACK,CYAN,OFF)", btn_off="(WHITE,BLUE,ON)",
        btn_key_on="(YELLOW,CYAN,ON)", btn_key_off="(YELLOW,BLUE,ON)",
        input="(BLACK,CYAN,OFF)", item="(CYAN,BLUE,ON)", sel="(BLACK,CYAN,OFF)",
        tag="(WHITE,BLUE,ON)", sel_tag="(BLACK,CYAN,OFF)", key="(YELLOW,BLUE,ON)",
        sel_key="(YELLOW,CYAN,ON)", arrow="(YELLOW,BLUE,ON)", status="(BLACK,CYAN,OFF)",
        gauge="(YELLOW,BLUE,ON)",
    ),
    # Windows 1.0: cyan desk, white windows, blue title plates.
    "windows": dict(
        name="Windows 1.0", mc="default", palette=CGA,
        screen="(BLACK,CYAN,OFF)", dialog="(BLACK,WHITE,OFF)", title="(WHITE,BLUE,ON)",
        border="(BLACK,WHITE,OFF)", border2="(BLACK,WHITE,OFF)",
        btn_on="(WHITE,BLACK,ON)", btn_off="(BLACK,WHITE,OFF)",
        btn_key_on="(WHITE,BLACK,ON)", btn_key_off="(BLUE,WHITE,OFF)",
        input="(BLACK,CYAN,OFF)", item="(BLACK,WHITE,OFF)", sel="(WHITE,BLUE,ON)",
        tag="(BLACK,WHITE,OFF)", sel_tag="(WHITE,BLUE,ON)", key="(BLUE,WHITE,OFF)",
        sel_key="(YELLOW,BLUE,ON)", arrow="(BLUE,WHITE,OFF)", status="(WHITE,BLUE,ON)",
        gauge="(BLUE,WHITE,OFF)",
    ),
    # Green phosphor monitor. The palette turns every program green.
    "green": dict(
        name="Green Screen (P1 phosphor)", mc="dark", shadow_on="OFF",
        palette=mono("0b3d0b", "1fb81f", "4dff4d"),
        screen="(GREEN,BLACK,OFF)", dialog="(GREEN,BLACK,OFF)", title="(GREEN,BLACK,ON)",
        border="(GREEN,BLACK,ON)", border2="(GREEN,BLACK,OFF)",
        btn_on="(BLACK,GREEN,OFF)", btn_off="(GREEN,BLACK,OFF)",
        btn_key_on="(BLACK,GREEN,OFF)", btn_key_off="(GREEN,BLACK,ON)",
        input="(GREEN,BLACK,ON)", item="(GREEN,BLACK,OFF)", sel="(BLACK,GREEN,OFF)",
        tag="(GREEN,BLACK,ON)", sel_tag="(BLACK,GREEN,OFF)", key="(GREEN,BLACK,ON)",
        sel_key="(BLACK,GREEN,OFF)", arrow="(GREEN,BLACK,ON)", status="(BLACK,GREEN,OFF)",
        gauge="(GREEN,BLACK,ON)",
    ),
    # Amber phosphor monitor.
    "amber": dict(
        name="Amber Screen (P3 phosphor)", mc="dark", shadow_on="OFF",
        palette=mono("4a2a00", "d98c00", "ffc34d"),
        screen="(YELLOW,BLACK,OFF)", dialog="(YELLOW,BLACK,OFF)", title="(YELLOW,BLACK,ON)",
        border="(YELLOW,BLACK,ON)", border2="(YELLOW,BLACK,OFF)",
        btn_on="(BLACK,YELLOW,OFF)", btn_off="(YELLOW,BLACK,OFF)",
        btn_key_on="(BLACK,YELLOW,OFF)", btn_key_off="(YELLOW,BLACK,ON)",
        input="(YELLOW,BLACK,ON)", item="(YELLOW,BLACK,OFF)", sel="(BLACK,YELLOW,OFF)",
        tag="(YELLOW,BLACK,ON)", sel_tag="(BLACK,YELLOW,OFF)", key="(YELLOW,BLACK,ON)",
        sel_key="(BLACK,YELLOW,OFF)", arrow="(YELLOW,BLACK,ON)", status="(BLACK,YELLOW,OFF)",
        gauge="(YELLOW,BLACK,ON)",
    ),
    # Windows 3.1's most famous colour scheme.
    "hotdog": dict(
        name="Hot Dog Stand", mc="default",
        palette="000000 ff0000 00aa00 ffff00 0000aa aa00aa 00aaaa aaaaaa 555555 ff5555 55ff55 ffff55 5555ff ff55ff 55ffff ffffff",
        screen="(YELLOW,RED,ON)", dialog="(BLACK,YELLOW,OFF)", title="(WHITE,RED,ON)",
        border="(RED,YELLOW,OFF)", border2="(RED,YELLOW,OFF)",
        btn_on="(YELLOW,RED,ON)", btn_off="(BLACK,YELLOW,OFF)",
        btn_key_on="(WHITE,RED,ON)", btn_key_off="(RED,YELLOW,OFF)",
        input="(YELLOW,RED,ON)", item="(BLACK,YELLOW,OFF)", sel="(WHITE,RED,ON)",
        tag="(RED,YELLOW,OFF)", sel_tag="(WHITE,RED,ON)", key="(RED,YELLOW,OFF)",
        sel_key="(YELLOW,RED,ON)", arrow="(RED,YELLOW,OFF)", status="(YELLOW,RED,ON)",
        gauge="(RED,YELLOW,OFF)",
    ),
}

for key, t in THEMES.items():
    d = os.path.join(ROOT, key)
    os.makedirs(d, exist_ok=True)
    with open(os.path.join(d, "dialogrc"), "w") as f:
        f.write(rc(t))
    with open(os.path.join(d, "name"), "w") as f:
        f.write(t["name"] + "\n")
    with open(os.path.join(d, "mc-skin"), "w") as f:
        f.write(t["mc"] + "\n")
    with open(os.path.join(d, "palette"), "w") as f:
        f.write("\n".join(t["palette"].split()) + "\n")
    print("wrote", key)
